// Mocks generated by Mockito 5.4.2 from annotations
// in flutter_application_camp/test/Features/Home/Data/DataSource/remote/remote_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_application_camp/Features/Home/Data/DataSource/remote/remote.dart'
    as _i2;
import 'package:flutter_application_camp/Features/Home/Domain/Entity/counteyEntity.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CountryDataRemoteImp].
///
/// See the documentation for Mockito's code generation for more information.
class MockCountryDataRemoteImp extends _i1.Mock
    implements _i2.CountryDataRemoteImp {
  MockCountryDataRemoteImp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CountryEntity>> getdata({String? item = r'AF'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getdata,
          [],
          {#item: item},
        ),
        returnValue:
            _i3.Future<List<_i4.CountryEntity>>.value(<_i4.CountryEntity>[]),
      ) as _i3.Future<List<_i4.CountryEntity>>);

  @override
  _i3.Future<bool> checkResponse() => (super.noSuchMethod(
        Invocation.method(
          #checkResponse,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
